In [34]:
import numpy as np
import pandas as pd

data = pd.read_csv(r"C:\Users\user\Downloads\Telegram Desktop\hepatitis.csv")  


print("First 10 samples:")
print(data.head(10))

print("\n3 random samples:")
print(data.sample(3))

print("\nLast 5 samples:")
print(data.tail(5))

print("Missing values:")
data.replace('?', np.nan, inplace=True)
column_info = pd.DataFrame({
    # "Columns": data.columns,
    "Feature Type": data.dtypes,     
    "Missing Values": data.isnull().sum()     
})

print(column_info)

print("Data types:")
column_infos = pd.DataFrame({
    "Type": data.dtypes
})
print(column_infos)

2

data.replace('?', np.nan, inplace=True)
missing_sample_indices = data[data.isnull().any(axis=1)].index
print(missing_sample_indices)
print("#######################################")
missing_features = data.columns[data.isnull().any()]
print(missing_features)
print("#######################################")
samples_with_missing_features = data[missing_features][data.isnull().any(axis=1)]
samples_with_missing_features
print("#######################################")
missing_values_count = data.isnull().sum()
print(missing_values_count)

print("#######################################")
cleaned_data = data.dropna()
cleaned_data

cleaned_data_columns = data.dropna(axis=1)
cleaned_data_columns

continuous_columns = data.select_dtypes(include=['float64', 'int64']).columns
categorical_columns = data.select_dtypes(include=['object']).columns

data[continuous_columns] = data[continuous_columns].fillna(data[continuous_columns].mean())

for column in categorical_columns:
    data[column] = data[column].fillna(data[column].mode()[0])

data

missing_values_after_imputation = data.isnull().sum()
print(missing_values_after_imputation)

C:\Users\user\AppData\Local\Temp\ipykernel_4372\1610562227.py:65: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[column] = data[column].fillna(data[column].mode()[0])

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.000000,18.0,4.0,61.852273,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.000000,42.0,3.5,61.852273,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.000000,32.0,4.0,61.852273,False,live
3,31,female,True,True,False,False,False,True,False,False,False,False,False,0.7,46.000000,52.0,4.0,80.000000,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,105.325397,200.0,4.0,61.852273,False,live
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,46,female,True,False,True,True,True,True,False,False,True,True,True,7.6,105.325397,242.0,3.3,50.000000,True,die
151,44,female,True,False,True,False,False,True,True,False,False,False,False,0.9,126.000000,142.0,4.3,61.852273,True,live
152,61,female,False,False,True,True,False,False,True,False,True,False,False,0.8,75.000000,20.0,4.1,61.852273,True,live
153,53,male,False,False,True,False,False,True,False,True,True,False,True,1.5,81.000000,19.0,4.1,48.000000,True,live
154,43,female,True,False,True,False,False,True,False,True,True,True,False,1.2,100.000000,19.0,3.1,42.000000,True,die

In [7]:
import numpy as np
import pandas as pd

data_file_path = r"C:\Users\user\OneDrive\Desktop\projects\tp2ML\hepatitis\hepatitis.data"
names_file_path = r"C:\Users\user\OneDrive\Desktop\projects\tp2ML\hepatitis\hepatitis.names"

def extract_column_names(names_file):
    column_names = []
    with open(names_file, 'r') as file:
        for i, line in enumerate(file, start=1):
            if 30 <= i <= 51:  # Only process lines 29 to 51
                line = line.strip()
                if line and not line.startswith("#"):
                    if ":" in line:
                        column_name = line.split(":")[0].strip()
                        column_names.append(column_name)
            if i > 51:  # Stop reading after line 51
                break
    return column_names

column_names = extract_column_names(names_file_path)
data = pd.read_csv(data_file_path, header=None, names=column_names)
data

Index([  0,   1,   2,   3,   4,   6,   7,   8,   9,  14,  16,  26,  31,  35,
        37,  41,  44,  45,  46,  50,  51,  55,  56,  59,  65,  66,  67,  69,
        70,  71,  72,  73,  74,  76,  79,  80,  83,  86,  87,  88,  91,  92,
        93,  97,  99, 101, 105, 106, 107, 110, 112, 113, 114, 115, 116, 118,
       119, 120, 122, 123, 126, 131, 132, 136, 140, 141, 142, 144, 146, 147,
       148, 149, 150, 151, 152],
      dtype='int64')